# In this demo we will use apache image (used image can be found on docker hub)
FROM httpd:2.4
COPY . /usr/local/apache2/htdocs/

# we can build this with - docker build . -t mywebapp:1
# We can run this with   - docker run -d -p 8080:80 mywebapp:1